# Generated by Django 4.2.13 on 2024-05-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Home Nursing', 'Home Nursing'), ('Physical Therapy', 'physical Therapy'), ('Speical Needs', 'Special Needs')], max_length=45)),
                ('patient_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('city', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('period', models.CharField(choices=[('8:00 AM to 16:00 PM', '8:00 AM to 16:00 PM'), ('16:00 PM to 12:00 AM', '16:00 PM to 12:00 AM'), ('12:00 AM to 8:00 AM', '12:00 AM to 8:00 AM')], max_length=45)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='homeCareApp.user')),
            ],
        ),
    ]
